import { generateId } from "@/lib/id";

export type IconDetails = typeof iconDetails;

export const iconDetails = {
  details: [
    {
      id: generateId(),
      title: "Problem",
      href: "/group.png",
      delay: "0",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 0,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
    },
    {
      id: generateId(),
      title: "Evaluate",
      href: "/group.png",
      delay: "0.3",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 30,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
    },
    {
      id: generateId(),
      title: "Develop",
      href: "/group.png",
      delay: "0.3",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 60,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
    },
    {
      id: generateId(),
      title: "Train",
      href: "/group.png",
      delay: "0.3",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 90,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
    },
    {
      id: generateId(),
      title: "Deploy",
      href: "/group.png",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 120,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
    },
    {
      id: generateId(),
      title: "Monitor",
      href: "/group.png",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 150,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
      items: [],
    },
    {
      id: generateId(),
      title: "Analytics",
      href: "/group.png",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 180,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
      items: [],
    },
    {
      id: generateId(),
      title: "Application",
      href: "/group.png",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 210,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
      items: [],
    },
    {
      id: generateId(),
      title: "Secure",
      href: "/group.png",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 240,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
      items: [],
    },
    {
      id: generateId(),
      title: "Insights",
      href: "/group.png",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 270,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
      items: [],
    },
    {
      id: generateId(),
      title: "Maintain",
      href: "/group.png",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 300,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
      items: [],
    },
    {
      id: generateId(),
      title: "connect",
      href: "/group.png",
      cx: "276",
      cy: "70",
      tx: "273",
      ty: "125",
      rotate: 330,
      description:
        "The ED401 stands out as our most versatile data logger device, boasting zero-touch configuration, multi-sensor support, compatibility with multiple protocols, and a portable design, making it a pivotal efficiency-enhancing device for a wide range of applications, including IIoT 4.0/5.0, Building Management Systems (BMS), and Green Energy use-cases.",
      items: [],
    },
  ],
};
